import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'qr_scan_page.dart';
import 'welcome_screen.dart';
import 'services/notification_service.dart';

final NotificationService notificationService = NotificationService();

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  await notificationService.init(); // Initialize the notification service
  runApp(const OneCardOneNationAppRoot());
}

class OneCardOneNationAppRoot extends StatefulWidget {
  const OneCardOneNationAppRoot({super.key});

  @override
  State<OneCardOneNationAppRoot> createState() => _OneCardOneNationAppRootState();
}

class _OneCardOneNationAppRootState extends State<OneCardOneNationAppRoot> {
  bool isDarkMode = false;

  void _toggleTheme(bool value) {
    setState(() => isDarkMode = value);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'One Card One Nation',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        fontFamily: 'Roboto',
        brightness: Brightness.light,
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF050238)),
        useMaterial3: true,
      ),
      darkTheme: ThemeData(
        fontFamily: 'Roboto',
        brightness: Brightness.dark,
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF050238), brightness: Brightness.dark),
        useMaterial3: true,
      ),
      themeMode: isDarkMode ? ThemeMode.dark : ThemeMode.light,
      home: WelcomeScreen(
        onThemeChanged: _toggleTheme,
        isDarkMode: isDarkMode,
      ),
    );
  }
}


