import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'qr_scan_page.dart';
import 'welcome_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const OneCardOneNationApp());
}

class OneCardOneNationApp extends StatelessWidget {
  const OneCardOneNationApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'One Card One Nation',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        fontFamily: 'Roboto',
        brightness: Brightness.light,
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF050238)),
        useMaterial3: true,
      ),
      home: const WelcomeScreen(), // or QRScanPage() if you want to start from there
    );
  }
}


